name: run

on: [push, pull_request]

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        polars-max-threads: [1, 2]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          python3 -mpip install -U pip
          python3 -mpip install polars numpy
          echo "Run generate.py"
          time python3 generate.py
          echo "Run convert.py"
          top -d60 -b -n30 &
          TOP_PID=$!
          time python3 convert.py
          kill $TOP_PID
        env:
          POLARS_MAX_THREADS: ${{ matrix.polars-max-threads }}