name: run

on: [push, pull_request]

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        polars-max-threads: [1, 2]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          python3 -mpip install -U pip
          python3 -mpip install polars numpy
          time python3 generate.py
          time python3 convert.py
        with:
          env:
            POLARS_MAX_THREADS: ${{ matrix.polars-max-threads }}